channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python >=3.8
  - ipython
  - numpy
  - pandas >=1
  - biopython
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - pytest
  - parallel
